# Generated by Django 3.0.5 on 2020-04-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_blogcomment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='First_Name',
            field=models.CharField(default='First Name', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='Last_Name',
            field=models.CharField(default='Last Name', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='Roll_No',
            field=models.CharField(default='ABC120', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='School',
            field=models.CharField(choices=[('SCHOOL OF COMPUTER ENGINEERING & TECHNOLOGY', 'SCHOOL OF COMPUTER ENGINEERING & TECHNOLOGY'), ('SCHOOL OF ELECTRICAL ENGINNERING', 'SCHOOL OF ELECTRICAL ENGINNERING'), ('SCHOOL OF MECHANICAL & CIVIL ENGINEERING', 'SCHOOL OF MECHANICAL & CIVIL ENGINEERING'), ('SCHOOL OF CHEMICAL ENGINEERING', 'SCHOOL OF CHEMICAL ENGINEERING'), ('SCHOOL OF HUMANITIES AND ENGINEERING SCIENCES', 'SCHOOL OF HUMANITIES AND ENGINEERING SCIENCES')], default='SCHOOL OF HUMANITIES AND ENGINEERING SCIENCES', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='Year',
            field=models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Final Year', 'Final Year')], default='First Year', max_length=50),
        ),
    ]
