# Generated by Django 3.0.5 on 2020-04-29 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0007_auto_20200429_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_event',
            name='register',
            field=models.ManyToManyField(blank=True, related_name='event_registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
