# Generated by Django 3.0.5 on 2020-04-30 00:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_post_event_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Roll_No', models.CharField(max_length=10)),
                ('Year', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.post_event')),
            ],
        ),
    ]
